destination: ./_site
lsi:         false
port: 4000
pygments:    true
markdown:    rdiscount
permalink: /:year/:month/:day/:title.html
url:         http://www.macwright.org/intersession/
rdiscount:
  extensions: [smart]
